In [32]:
import pandas as pd

In [33]:
import numpy as np

In [34]:
df=pd.read_csv("C:/Users/jasan/OneDrive/Desktop/gujarat.csv")

In [35]:
df1=pd.read_csv("C:/Users/jasan/OneDrive/Desktop/Maharashtra.csv")

In [36]:
df2=pd.read_csv("C:/Users/jasan/OneDrive/Desktop/Goa.csv")

In [37]:
df3=pd.read_csv("C:/Users/jasan/OneDrive/Desktop/andaman.csv")

In [38]:
df

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,Gujarat,1146.0,107.0,95.0,1146.0,0.0,592.0,554.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1146.0
1,17/01/2021,Gujarat,2313.0,351.0,189.0,2313.0,0.0,1118.0,1195.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2313.0
2,18/01/2021,Gujarat,2182.0,598.0,287.0,2182.0,0.0,1071.0,1111.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2182.0
3,19/01/2021,Gujarat,4842.0,700.0,313.0,4842.0,0.0,2412.0,2430.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4842.0
4,20/01/2021,Gujarat,4877.0,932.0,409.0,4877.0,0.0,2426.0,2451.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4877.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,8/8/2021,Gujarat,36596532.0,862886.0,3011.0,27636206.0,8960326.0,19956647.0,16634349.0,5536.0,...,16485080.0,11780803.0,8330649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,9/8/2021,Gujarat,37152375.0,1008804.0,3360.0,28101222.0,9051153.0,20266401.0,16880326.0,5648.0,...,16854786.0,11912298.0,8385291.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df4=pd.concat([df,df1,df2,df3])

In [40]:
df4

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,18-44 Years (Doses Administered),45-60 Years (Doses Administered),60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,Gujarat,1146.0,107.0,95.0,1146.0,0.0,592.0,554.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1146.0
1,17/01/2021,Gujarat,2313.0,351.0,189.0,2313.0,0.0,1118.0,1195.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2313.0
2,18/01/2021,Gujarat,2182.0,598.0,287.0,2182.0,0.0,1071.0,1111.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2182.0
3,19/01/2021,Gujarat,4842.0,700.0,313.0,4842.0,0.0,2412.0,2430.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4842.0
4,20/01/2021,Gujarat,4877.0,932.0,409.0,4877.0,0.0,2426.0,2451.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4877.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,8/8/2021,Andaman and Nicobar Islands,309349.0,540.0,2.0,215077.0,94272.0,164902.0,144407.0,40.0,...,117991.0,127835.0,63523.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,9/8/2021,Andaman and Nicobar Islands,310643.0,5325.0,31.0,216046.0,94597.0,165554.0,145049.0,40.0,...,118865.0,128122.0,63656.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
df4=df4.drop(columns=['18-44 Years (Doses Administered)','45-60 Years (Doses Administered)','45-60 Years (Doses Administered)'])
#dropped unnecessary columns

In [42]:
df4

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,Sputnik V (Doses Administered),AEFI,60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,Gujarat,1146.0,107.0,95.0,1146.0,0.0,592.0,554.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1146.0
1,17/01/2021,Gujarat,2313.0,351.0,189.0,2313.0,0.0,1118.0,1195.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2313.0
2,18/01/2021,Gujarat,2182.0,598.0,287.0,2182.0,0.0,1071.0,1111.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2182.0
3,19/01/2021,Gujarat,4842.0,700.0,313.0,4842.0,0.0,2412.0,2430.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4842.0
4,20/01/2021,Gujarat,4877.0,932.0,409.0,4877.0,0.0,2426.0,2451.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4877.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,8/8/2021,Andaman and Nicobar Islands,309349.0,540.0,2.0,215077.0,94272.0,164902.0,144407.0,40.0,...,0.0,5.0,63523.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,9/8/2021,Andaman and Nicobar Islands,310643.0,5325.0,31.0,216046.0,94597.0,165554.0,145049.0,40.0,...,0.0,5.0,63656.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df4=df4.fillna(0)

In [44]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 836 entries, 0 to 208
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Updated On                           836 non-null    object
 1   State                                836 non-null    object
 2   Total Doses Administered             836 non-null    float64
 3   Sessions                             836 non-null    float64
 4    Sites                               836 non-null    float64
 5   First Dose Administered              836 non-null    float64
 6   Second Dose Administered             836 non-null    float64
 7   Male (Doses Administered)            836 non-null    float64
 8   Female (Doses Administered)          836 non-null    float64
 9   Transgender (Doses Administered)     836 non-null    float64
 10   Covaxin (Doses Administered)        836 non-null    float64
 11  CoviShield (Doses Administered)      836 non-null    float64
 12  Sputnik V (Doses Administered)       836 non-null    float64
 13  AEFI                                 836 non-null    float64
 14  60+ Years (Doses Administered)       836 non-null    float64
 15  18-44 Years(Individuals Vaccinated)  836 non-null    float64
 16  45-60 Years(Individuals Vaccinated)  836 non-null    float64
 17  60+ Years(Individuals Vaccinated)    836 non-null    float64
 18  Male(Individuals Vaccinated)         836 non-null    float64
 19  Female(Individuals Vaccinated)       836 non-null    float64
 20  Transgender(Individuals Vaccinated)  836 non-null    float64
 21  Total Individuals Vaccinated         836 non-null    float64
dtypes: float64(20), object(2)
memory usage: 150.2+ KB

In [45]:
for i in df4.columns:
    try:
        df4[[i]] = df4[[i]].astype(float).astype(int)
    except:
        pass

In [46]:
df4

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,Sputnik V (Doses Administered),AEFI,60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,Gujarat,1146,107,95,1146,0,592,554,0,...,0,0,0,0,0,0,0,0,0,1146
1,17/01/2021,Gujarat,2313,351,189,2313,0,1118,1195,0,...,0,0,0,0,0,0,0,0,0,2313
2,18/01/2021,Gujarat,2182,598,287,2182,0,1071,1111,0,...,0,0,0,0,0,0,0,0,0,2182
3,19/01/2021,Gujarat,4842,700,313,4842,0,2412,2430,0,...,0,0,0,0,0,0,0,0,0,4842
4,20/01/2021,Gujarat,4877,932,409,4877,0,2426,2451,0,...,0,0,0,0,0,0,0,0,0,4877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,8/8/2021,Andaman and Nicobar Islands,309349,540,2,215077,94272,164902,144407,40,...,0,5,63523,0,0,0,0,0,0,0
205,9/8/2021,Andaman and Nicobar Islands,310643,5325,31,216046,94597,165554,145049,40,...,0,5,63656,0,0,0,0,0,0,0
206,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
207,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
208,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [47]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 836 entries, 0 to 208
Data columns (total 22 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Updated On                           836 non-null    object
 1   State                                836 non-null    object
 2   Total Doses Administered             836 non-null    int32
 3   Sessions                             836 non-null    int32
 4    Sites                               836 non-null    int32
 5   First Dose Administered              836 non-null    int32
 6   Second Dose Administered             836 non-null    int32
 7   Male (Doses Administered)            836 non-null    int32
 8   Female (Doses Administered)          836 non-null    int32
 9   Transgender (Doses Administered)     836 non-null    int32
 10   Covaxin (Doses Administered)        836 non-null    int32
 11  CoviShield (Doses Administered)      836 non-null    int32
 12  Sputnik V (Doses Administered)       836 non-null    int32
 13  AEFI                                 836 non-null    int32
 14  60+ Years (Doses Administered)       836 non-null    int32
 15  18-44 Years(Individuals Vaccinated)  836 non-null    int32
 16  45-60 Years(Individuals Vaccinated)  836 non-null    int32
 17  60+ Years(Individuals Vaccinated)    836 non-null    int32
 18  Male(Individuals Vaccinated)         836 non-null    int32
 19  Female(Individuals Vaccinated)       836 non-null    int32
 20  Transgender(Individuals Vaccinated)  836 non-null    int32
 21  Total Individuals Vaccinated         836 non-null    int32
dtypes: int32(20), object(2)
memory usage: 84.9+ KB

In [48]:
df4=df4[df4['State']!=0]

In [49]:
df4

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,Sputnik V (Doses Administered),AEFI,60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,Gujarat,1146,107,95,1146,0,592,554,0,...,0,0,0,0,0,0,0,0,0,1146
1,17/01/2021,Gujarat,2313,351,189,2313,0,1118,1195,0,...,0,0,0,0,0,0,0,0,0,2313
2,18/01/2021,Gujarat,2182,598,287,2182,0,1071,1111,0,...,0,0,0,0,0,0,0,0,0,2182
3,19/01/2021,Gujarat,4842,700,313,4842,0,2412,2430,0,...,0,0,0,0,0,0,0,0,0,4842
4,20/01/2021,Gujarat,4877,932,409,4877,0,2426,2451,0,...,0,0,0,0,0,0,0,0,0,4877
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,5/8/2021,Andaman and Nicobar Islands,307014,5504,30,213457,93557,163740,143234,40,...,0,5,63300,0,0,0,0,0,0,0
202,6/8/2021,Andaman and Nicobar Islands,308177,4193,29,214333,93844,164339,143798,40,...,0,5,63432,0,0,0,0,0,0,0
203,7/8/2021,Andaman and Nicobar Islands,309270,5149,29,215021,94249,164868,144362,40,...,0,5,63522,0,0,0,0,0,0,0
204,8/8/2021,Andaman and Nicobar Islands,309349,540,2,215077,94272,164902,144407,40,...,0,5,63523,0,0,0,0,0,0,0
205,9/8/2021,Andaman and Nicobar Islands,310643,5325,31,216046,94597,165554,145049,40,...,0,5,63656,0,0,0,0,0,0,0

In [50]:
df4.head()

,Updated On,State,Total Doses Administered,Sessions,Sites,First Dose Administered,Second Dose Administered,Male (Doses Administered),Female (Doses Administered),Transgender (Doses Administered),...,Sputnik V (Doses Administered),AEFI,60+ Years (Doses Administered),18-44 Years(Individuals Vaccinated),45-60 Years(Individuals Vaccinated),60+ Years(Individuals Vaccinated),Male(Individuals Vaccinated),Female(Individuals Vaccinated),Transgender(Individuals Vaccinated),Total Individuals Vaccinated
0,16/01/2021,Gujarat,1146,107,95,1146,0,592,554,0,...,0,0,0,0,0,0,0,0,0,1146
1,17/01/2021,Gujarat,2313,351,189,2313,0,1118,1195,0,...,0,0,0,0,0,0,0,0,0,2313
2,18/01/2021,Gujarat,2182,598,287,2182,0,1071,1111,0,...,0,0,0,0,0,0,0,0,0,2182
3,19/01/2021,Gujarat,4842,700,313,4842,0,2412,2430,0,...,0,0,0,0,0,0,0,0,0,4842
4,20/01/2021,Gujarat,4877,932,409,4877,0,2426,2451,0,...,0,0,0,0,0,0,0,0,0,4877

In [74]:
#Check unique values
df4.nunique()

Updated On                             206
State                                    4
Total Doses Administered               795
Sessions                               746
 Sites                                 506
First Dose Administered                794
Second Dose Administered               681
Male (Doses Administered)              794
Female (Doses Administered)            791
Transgender (Doses Administered)       403
 Covaxin (Doses Administered)          494
CoviShield (Doses Administered)        795
Sputnik V (Doses Administered)         101
AEFI                                   306
60+ Years (Doses Administered)         185
18-44 Years(Individuals Vaccinated)    399
45-60 Years(Individuals Vaccinated)    400
60+ Years(Individuals Vaccinated)      397
Male(Individuals Vaccinated)             1
Female(Individuals Vaccinated)           1
Transgender(Individuals Vaccinated)      1
Total Individuals Vaccinated           611
dtype: int64

In [75]:
#cleaning the data
df4.isnull().sum()

Updated On                             0
State                                  0
Total Doses Administered               0
Sessions                               0
 Sites                                 0
First Dose Administered                0
Second Dose Administered               0
Male (Doses Administered)              0
Female (Doses Administered)            0
Transgender (Doses Administered)       0
 Covaxin (Doses Administered)          0
CoviShield (Doses Administered)        0
Sputnik V (Doses Administered)         0
AEFI                                   0
60+ Years (Doses Administered)         0
18-44 Years(Individuals Vaccinated)    0
45-60 Years(Individuals Vaccinated)    0
60+ Years(Individuals Vaccinated)      0
Male(Individuals Vaccinated)           0
Female(Individuals Vaccinated)         0
Transgender(Individuals Vaccinated)    0
Total Individuals Vaccinated           0
dtype: int64

In [51]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\jasan\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\jasan\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [52]:
df4.to_excel('cvdata.xlsx')